name: Build and Deploy Frontend

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/deploy-frontend.yml

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: npm install, build
        run: |
          npm ci
          npm run build
        working-directory: "frontend/"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: node-build-cache
          key: ${{ runner.os }}-node-build-cache-${{ hashFiles('**/frontend/package-lock.json') }}

      - name: inject build-cache into docker
        uses: overmindtech/buildkit-cache-dance/inject@main
        with:
          cache-source: node-build-cache

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/frontend/
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ github.workspace }}/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/yt-downloader:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/yt-downloader:latest
          platforms: linux/amd64

      - name: extract build-cache from docker
        uses: overmindtech/buildkit-cache-dance/extract@main
        with:
          cache-source: node-build-cache

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/yt-downloader/frontend/ && ./exec.sh ${{ secrets.DOCKER_PASSWORD }} && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
