name: Build and Deploy Backend

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: "backend/"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: pip-build-cache
          key: ${{ runner.os }}-pip-build-cache-${{ hashFiles('**/backend/requirements.txt') }}

      - name: inject build-cache into docker
        uses: overmindtech/buildkit-cache-dance/inject@main
        with:
          cache-source: pip-build-cache

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/backend/
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ github.workspace }}/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/yt-downloader-backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/yt-downloader-backend:latest
          build-args: |
            SERVICE_ACCOUNT_JSON=${{ secrets.SERVICE_ACCOUNT_JSON }}
            FIREBASE_SERVICE_ACCOUNT_KEY_PATH=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_PATH }}
          platforms: linux/amd64,linux/arm64

      - name: extract build-cache from docker
        uses: overmindtech/buildkit-cache-dance/extract@main
        with:
          cache-source: pip-build-cache

      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/yt-downloader/backend/ && ./exec.sh ${{ secrets.DOCKER_PASSWORD }} && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
